# Generated by Django 4.2.3 on 2023-08-20 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_amount_cartitem_quantity_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='product',
        ),
    ]
