# Generated by Django 4.2.3 on 2023-08-21 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_deliverystatus_updated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='order',
        ),
    ]
