# Generated by Django 4.2.3 on 2023-08-21 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_cart_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='organization',
        ),
    ]
