# Generated by Django 4.2.3 on 2023-08-22 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_cartitem_product_alter_orderitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='updated_at',
        ),
    ]
