# Generated by Django 4.2.3 on 2023-08-22 09:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_feedback_slug_remove_feedback_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
