# Generated by Django 4.2.3 on 2023-08-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('we', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
