# Generated by Django 4.2.3 on 2023-08-16 07:58

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('we', '0002_organizationuser_is_active_organizationuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='user__name', unique=True),
        ),
    ]
