# Generated by Django 4.2.3 on 2023-08-16 08:04

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('we', '0003_alter_rating_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='name',
            field=models.CharField(default='rating', max_length=255),
        ),
        migrations.AlterField(
            model_name='rating',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
    ]
