# Generated by Django 4.2.3 on 2023-08-16 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('we', '0004_rating_name_alter_rating_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='name',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='updated_at',
        ),
    ]
