# Generated by Django 4.2.3 on 2023-08-09 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('we', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='Product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='we.product'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders_management.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='we.organization'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='Order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders_management.order'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='we.product'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverystatus',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders_management.order'),
        ),
        migrations.AddField(
            model_name='deliverystatus',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders_management.cart'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='we.product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders_management.order'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
