# Generated by Django 4.2.3 on 2023-08-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_management', '0002_alter_cart_uid_alter_cartitem_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
