# Generated by Django 4.2.3 on 2023-08-16 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_management', '0003_alter_cartitem_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='stock',
            new_name='amount',
        ),
    ]
